{
 "title": "Prometheus / Graphite remote adapter",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(up, cluster)" } },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(go_memstats_alloc_bytes{cluster=\"$cluster\",job!=\"kube-apiserver\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(process_resident_memory_bytes{cluster=\"$cluster\",namespace=\"$namespace\", job!=\"kube-apiserver\"}, pod)"
    }
   },
   {
    "name": "interval",
    "query": "1m,5m,10m,15m,30m,1h,3h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  { "title": "Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Received / Sent / Failed (Instant)",
   "type": "stat",
   "description": "Total number of received samples.\nTotal number of processed samples sent to remote \nstorage.\nTotal number of processed samples which failed on send to remote storage.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(remote_adapter_received_samples_total{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[5m]) OR on() vector(0)",
     "legendFormat": "Received"
    },
    {
     "expr": "rate(remote_adapter_sent_samples_total{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[5m]) OR on() vector(0)",
     "legendFormat": "Sent"
    },
    {
     "expr": "rate(remote_adapter_failed_samples_total{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[5m]) OR on() vector(0)",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Received / Sent / Failed",
   "type": "graph",
   "description": "Total number of received samples.\nTotal number of processed samples sent to remote \nstorage.\nTotal number of processed samples which failed on send to remote storage.\n",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(remote_adapter_received_samples_total{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[5m])"
    },
    {
     "expr": "rate(remote_adapter_sent_samples_total{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[5m])"
    },
    {
     "expr": "rate(remote_adapter_failed_samples_total{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[5m])"
    }
   ]
  },
  {
   "title": "Received Samples",
   "type": "graph",
   "description": "Total number of received samples",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(remote_adapter_received_samples_total{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[5m])",
     "legendFormat": "{{namespace}}:{{pod}}"
    }
   ]
  },
  {
   "title": "Processed Samples",
   "type": "graph",
   "description": "Total number of processed samples sent to remote storage",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(remote_adapter_sent_samples_total{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[5m])",
     "legendFormat": "{{namespace}}:{{pod}}"
    }
   ]
  },
  {
   "title": "Failed samples",
   "type": "graph",
   "description": "Total number of processed samples which failed on send to remote storage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(remote_adapter_failed_samples_total{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[5m]) OR on() vector(0)",
     "legendFormat": "{{namespace}}:{{pod}}"
    }
   ]
  },
  {
   "title": "Sent samples duration",
   "type": "graph",
   "description": "Duration of sample batch send calls to the remote storage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(remote_adapter_sent_batch_duration_seconds_count{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[5m])",
     "legendFormat": "{{namespace}}:{{pod}}"
    }
   ]
  },
  {
   "title": "Go process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "Total user and system CPU time spent in seconds.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short", "label": "Millicores" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[5m]) * 1000",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Process memory",
     "type": "graph",
     "description": "Shows resident and virtual memory volume",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}} - resident"
      },
      {
       "expr": "process_virtual_memory_bytes{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}} - virtual"
      }
     ]
    },
    {
     "title": "Process memory / second",
     "type": "graph",
     "description": "Shows per-second memory rate",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(process_resident_memory_bytes{namespace=\"$namespace\",pod=~\"$pod\"}[2m])",
       "legendFormat": "{{pod}} - resident"
      },
      {
       "expr": "deriv(process_virtual_memory_bytes{namespace=\"$namespace\",pod=~\"$pod\"}[2m])",
       "legendFormat": "{{pod}} - virtual"
      }
     ]
    },
    {
     "title": "Go memstats",
     "type": "graph",
     "description": "Shows how much Go is using from the amount of memory the Prometheus process is using from the kernel",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{namespace=\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}} - bytes allocated"
      },
      {
       "expr": "rate(go_memstats_alloc_bytes_total{namespace=\"$namespace\",pod=~\"$pod\"}[30s])",
       "legendFormat": "{{pod}} - alloc rate"
      },
      {
       "expr": "go_memstats_stack_inuse_bytes{namespace=\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}} - stack inuse"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{namespace=\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}} - heap inuse"
      }
     ]
    },
    {
     "title": "Go memstats / second",
     "type": "graph",
     "description": "Shows per-second rate of how much Go is using from the amount of memory the Prometheus process is using from the kernel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "deriv(go_memstats_alloc_bytes{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[2m])",
       "legendFormat": "{{pod}} - bytes allocated"
      },
      {
       "expr": "rate(go_memstats_alloc_bytes_total{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[2m])",
       "legendFormat": "{{pod}} - alloc rate"
      },
      {
       "expr": "deriv(go_memstats_stack_inuse_bytes{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[2m])",
       "legendFormat": "{{pod}} - stack inuse"
      },
      {
       "expr": "deriv(go_memstats_heap_inuse_bytes{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[2m])",
       "legendFormat": "{{pod}} - heap inuse"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "description": "Shows the number of goroutined that currently exists",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{cluster=~\"$cluster\",namespace=\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "GC duration quantiles",
     "type": "graph",
     "description": "Shows  the summary of the GC invocation durations",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{cluster=~\"$cluster\",namespace=\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}}: {{quantile}}"
      }
     ]
    }
   ]
  },
  {
   "title": "API Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Handle API request duration, 99th quantile",
     "type": "graph",
     "description": "A histogram of latencies for requests.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(remote_adapter_api_request_duration_seconds_bucket{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[5m])) by (handler, le))",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "API Response size, 99th quantile",
     "type": "graph",
     "description": "A histogram of response sizes for requests.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(remote_adapter_api_response_size_bytes_bucket[5m])) by (handler, le))",
       "legendFormat": "{{handler}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sent metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sent batch duration",
     "type": "graph",
     "description": "Duration of sample batch send calls to the remote storage.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(remote_adapter_sent_batch_duration_seconds_bucket[5m])) by (le))"
      }
     ]
    },
    {
     "title": "Sent samples",
     "type": "graph",
     "description": "Total number of processed samples sent to remote storage.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(remote_adapter_sent_samples_total{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[5m])",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Promhttp",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Handled requests",
     "type": "graph",
     "description": "Total number of scrapes by HTTP status code.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(promhttp_metric_handler_requests_total{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[1m])",
       "legendFormat": "{{code}}:{{pod}}"
      }
     ]
    },
    {
     "title": "Requests in-flight",
     "type": "graph",
     "description": "Current number of scrapes being served.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "promhttp_metric_handler_requests_in_flight{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}